# version: "3.9"
services:
  # MySQL for the source node
  dlt_mysql_source:
    image: mysql:5.7
    container_name: dlt_mysql_source
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbzains
      MYSQL_USER: symuser
      MYSQL_PASSWORD: sympass
    ports:
      - "3307:3306"
    networks:
      - sym_network
    volumes:
      - ./mysql_source_data:/var/lib/mysql

  # MySQL for the target node
  dlt_mysql_target:
    image: arm64v8/mysql:8.4
    container_name: dlt_mysql_target
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbzains
      MYSQL_USER: symuser
      MYSQL_PASSWORD: sympass
    ports:
      - "3308:3306"
    networks:
      - sym_network
    volumes:
      - ./mysql_target_data:/var/lib/mysql

  dlt_runner:
    build: .  # Build from the Dockerfile in the current directory
    container_name: dlt_runner
    restart: always
    depends_on:
      - dlt_mysql_source
      - dlt_mysql_target
    volumes:
      - ./source:/app
      - ./logs:/var/log/app
    networks:
      - sym_network

networks:
  sym_network:
    driver: bridge

